- name: variable with prompt
  hosts: web
  vars_prompt:
  - name: NAME
    prompt: Please enter the name
  - name: DESIGNATION
    prompt: Please enter the Designation....
  - name: LOCATION
    prompt: Please enter the location...
  tasks:
  - name: User Details 
    ansible.builtin.debug:
      msg: "my nsme is {{NAME}},designation and location"  