- name: loops
 hosts: local
 connection: local
 tasks:
 - name: installing packages
   ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.present}}"
   loop: 
  - {name: 'mysql', state: 'present' }
  - {name: 'nginx', state: 'absent'}

