- name: create ec2 and r53 instance
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0ff9ee20edf0ed71f
    sg_id: "sg-02fc3e5136234f59b"
    ami_id: "ami-09c813fb71547fc4f"
    instances: 
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name:  "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2

  - name: output
    ansible.builtin.debug:
      msg: "output {{ ec2}}"
